#ifndef DCL_SHUNT_DEFINE_H
#define DCL_SHUNT_DEFINE_H

#include <QString>

enum WORKSTATE{
    _WAITE,
    _READY,
    _WORKING,
    _PAUSE,
    _STOP
};

enum ANORMALWORK{
    SACNERCONNECTFAILE,
    MESCONNECTFAILE,
    PLCCONNECTFAILE,
    SPORTSCARDCONNECTFAILE,
    SACNERDATAERROR,
    MESDATAERROR,
    PLCDATAERROR,
    SPORTSCARDDATAERROR,
    SACNERWARING,
    MESWARING,
    PLCWARING,
    SPORTSCARDWARING,
    BOXERROR,
};


#endif // DCL_SHUNT_DEFINE_H
